declare const CACHE: KVNamespace
declare const SUPABASE_URL: string
declare const SUPABASE_API_KEY: string
declare const PROVIDER_F_API_ID: string
declare const PROVIDER_F_AFF_ID: string
declare const AWS_ACCESS_KEY_ID: string
declare const AWS_SECRET_ACCESS_KEY: string
declare const AWS_DEFAULT_REGION: string
declare const JOB_DEFINITION_FOR_DOWNLOAD: string
declare const JOB_DEFINITION_FOR_COMPRESSION: string
declare const JOB_QUEUE: string
declare const JOB_QUEUE_FOR_HIGH: string
