name = "power-plant"
type = "javascript"

zone_id = ""
account_id = ""
route = ""
workers_dev = true

kv_namespaces = [{ binding = "CACHE", id = "051f6a0408304a24bef9e373453388a0", preview_id = "eca8e3ee3aae4478ae0fe28ffc6e76de" }]

[site]
bucket = "./public"
entry-point = "."

[build]
command = "npm run build"

[build.upload]
format="service-worker"