name = "power-plant-bindee"

compatibility_date = "2022-05-11"

account_id = ""
workers_dev = true
main = "./build/index.js"

[[kv_namespaces]]
binding = "CACHE"
id = "051f6a0408304a24bef9e373453388a0"
preview_id = "eca8e3ee3aae4478ae0fe28ffc6e76de"

[site]
bucket = "./public"

[build]
command = "DEPLOY=true BINDEE=true npm run build"