name: Batch Job

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-18.04
    timeout-minutes: 300

    steps:
      - uses: actions/checkout@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPO_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-northeast-1
          BUCKET: transmission-project
          KEY_PREFIX: power-plant
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest --build-arg AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID --build-arg AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY --build-arg AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION --build-arg BUCKET=$BUCKET --build-arg KEY_PREFIX=$KEY_PREFIX --build-arg DATABASE_URL=$DATABASE_URL -f batch/Dockerfile .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

  serverless-deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install && yarn serverless deploy --stage=production
        working-directory: ./batch/serverless
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-northeast-1
          JOB_DEFINITION: ${{ secrets.JOB_DEFINITION }}
          JOB_QUEUE: ${{ secrets.JOB_QUEUE }}
          SEVERLESS_EXECUTE_ROLE: ${{ SEVERLESS_EXECUTE_ROLE }}
