name: Deploy Remix

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Publish Worker
        uses: cloudflare/wrangler-action@1.3.0
        with:
          workingDirectory: remix
          apiToken: ${{ secrets.CF_API_TOKEN }}
          preCommands: yarn
          postCommands: yarn deploy
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}