name: Deploy Remix

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
    timeout-minutes: 60
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          yarn install
          yarn global add @cloudflare/wrangler
          yarn deploy
        working-directory: './remix'
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_API_KEY: ${{ secrets.SUPABASE_API_KEY }}
          BATCH_JOB_SLS_ENDPOINT: ${{ secrets.BATCH_JOB_SLS_ENDPOINT }}
          PROVIDER_F_API_ID: ${{ secrets.PROVIDER_F_API_ID }}
          PROVIDER_F_AFF_ID: ${{ secrets.PROVIDER_F_AFF_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-northeast-1
          JOB_DEFINITION: ${{ secrets.JOB_DEFINITION }}
          JOB_QUEUE: ${{ secrets.JOB_QUEUE }}
