name: Deploy Remix

on:
  push:
    branches:
      - main
    paths:
      - remix/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        working-directory: './remix'
        run: yarn install --frozen-lockfile
      - name: Deploy 🚀
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: './remix'
          preCommands: |
            yarn generate
            echo $SUPABASE_URL | wrangler secret put SUPABASE_URL
            echo $SUPABASE_API_KEY | wrangler secret put SUPABASE_API_KEY
            echo $PROVIDER_F_API_ID | wrangler secret put PROVIDER_F_API_ID
            echo $PROVIDER_F_AFF_ID | wrangler secret put PROVIDER_F_AFF_ID
            echo $AWS_ACCESS_KEY_ID | wrangler secret put AWS_ACCESS_KEY_ID
            echo $AWS_SECRET_ACCESS_KEY | wrangler secret put AWS_SECRET_ACCESS_KEY
            echo $AWS_DEFAULT_REGION | wrangler secret put AWS_DEFAULT_REGION
            echo $JOB_DEFINITION_FOR_DOWNLOAD | wrangler secret put JOB_DEFINITION_FOR_DOWNLOAD
            echo $JOB_DEFINITION_FOR_COMPRESSION | wrangler secret put JOB_DEFINITION_FOR_COMPRESSION
            echo $JOB_QUEUE | wrangler secret put JOB_QUEUE
            echo $JOB_QUEUE_FOR_HIGH | wrangler secret put JOB_QUEUE_FOR_HIGH
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_API_KEY: ${{ secrets.SUPABASE_API_KEY }}
          PROVIDER_F_API_ID: ${{ secrets.PROVIDER_F_API_ID }}
          PROVIDER_F_AFF_ID: ${{ secrets.PROVIDER_F_AFF_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-northeast-1
          JOB_DEFINITION_FOR_DOWNLOAD: ${{ secrets.JOB_DEFINITION_FOR_DOWNLOAD }}
          JOB_DEFINITION_FOR_COMPRESSION: ${{ secrets.JOB_DEFINITION_FOR_COMPRESSION }}
          JOB_QUEUE: ${{ secrets.JOB_QUEUE }}
          JOB_QUEUE_FOR_HIGH: ${{ secrets.JOB_QUEUE_FOR_HIGH }}