name: Transmission EC2 job

on:
  workflow_dispatch:
    inputs:
      mode:
        type: choice
        description: run or stop
        required: true
        options:
          - run
          - stop
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ap-northeast-1

jobs:
  ec2-run-or-stop:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.3

      - name: Run
        if: ${{ github.event.inputs.mode }} == 'run'
        working-directory: ./terraform/transmission
        run: terraform apply -auto-approve

      - name: Stop
        if: ${{ github.event.inputs.mode }} == 'stop'
        working-directory: ./terraform/transmission
        run: terraform destory -auto-approve
